### ISSUE TITLE
Attribute & Relationship Knowledge GroundTruth

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [chanyn/HKRM#1]
Hello,
I can not find any information about collecting ground truth of  attribute and relationship knowledge. How do you get  these ground-truth? 

Thanks in advance.

**Comment by chanyn** [comment]
Hi, we described that how to build ground-truth graph in Section 4 Knowledge Graph Construction. In Visual Genome datasets, you can get each object attribute annotation and relationship annotation between objects.
In brief, we sum each object attribute annotation of entire dataset if the class of object is in the top 3000 frequent categories we had defined, so we get a  3000*D frequency statistic matrix.
For relationship frequency statistic matrix, we first new a 3000*3000 zero matrix Qr. Then we check the ground-truth of each relationship annotation and add 1 to the corresponding position of Qr, if both classes are in the range of top 3000 frequent categories.
We think the above operation is easy to implement, and we have provided attribute and relationship frequency statistic matrix in README.

**Comment by Bedrettin-Cetinkaya** [comment]
Thanks for your quick answer.
Actually, i want to ask that how do you collect ground truth for  pascal voc and ms-coco dataset? I forgot to specify datasets.

**Comment by Easyfeng222** [comment]
@Bedrettin-Cetinkaya  Excuse me, have you implemented this paper?

**Comment by Easyfeng222** [comment]
@Bedrettin-Cetinkaya  Excuse me, have you encountered this problem?
FileNotFoundError: [Errno 2] No such file or directory: '/data/Detection/vg/objects_val.json'

**Comment by chanyn** [comment]
Oh, we collect coco/voc gt graph by matching classes names with VG.  I have released corresponding code in lib/datasets/collect_coco_voc_gtgraph.py
First, you should download attribute/relationship frequency statistic matrix. Second, you should save your dataset classes names. We provide VG names (VG_3000_name_to_ind.pkl) and COCO names (coco_name.pkl).

**Comment by Easyfeng222** [comment]
@chanyn Excuse me ,I have downloaded Visual Genome (v1.4), but this problem occurs when testing.
AssertionError: Path does not exist: /home/feng/HKRM/data/Detection/vg/VG/2408452.jpg
My terminal command is:
python3 test_net.py --dataset vg --net HKRM   --load_dir /home/feng/HKRM/save --checksession 325 --checkepoch 12 --checkpoint 21985

**Comment by Easyfeng222** [comment]
Excuse me ,I have downloaded Visual Genome (v1.4), but this problem occurs when testing.
 @chanyn AssertionError: Path does not exist: /home/feng/HKRM/data/Detection/vg/VG/2408452.jpg
My terminal command is:
python3 test_net.py --dataset vg --net HKRM --load_dir /home/feng/HKRM/save --checksession 325 --checkepoch 12 --checkpoint 21985
I want to know the relationship between vg datasets and vg_val_gt_roidb.pkl you mentioned.Thank you in advance

**Comment by Easyfeng222** [comment]
@chanyn Excuse me ,I have downloaded Visual Genome (v1.4), but this problem occurs when testing.
AssertionError: Path does not exist: /home/feng/HKRM/data/Detection/vg/VG/2408452.jpg
My terminal command is:
python3 test_net.py --dataset vg --net HKRM --load_dir /home/feng/HKRM/save --checksession 325 --checkepoch 12 --checkpoint 21985
I want to know the relationship between vg datasets and vg_val_gt_roidb.pkl you mentioned.And vg val (5000)is on these VG datasets ???Thank you in advance

**Comment by Easyfeng222** [comment]
@chanyn When I change 1 to 2 ,cls_dets = torch.cat((cls_boxes, cls_scores), 2)
Traceback (most recent call last):
  File "test_net.py", line 337, in <module>
    cls_dets = torch.cat((cls_boxes, cls_scores), 2)
RuntimeError: dim out of range - got 2 but the tensor is only 2D
