### ISSUE TITLE
这代码是不是不支持pascal voc和coco数据集的训练啊

### ISSUE THREAD

**Issue by summerrr** [chanyn/HKRM#11]
if args.dataset == "vg":
      args.imdb_name = "vg_train"
      args.imdbval_name = "vg_val"
      args.set_cfgs = ['ANCHOR_SCALES', '[2, 4, 8, 16, 32]', 'MAX_NUM_GT_BOXES', '50']
      cls_r_prob = pickle.load(open('data/graph/vg_graph_r.pkl', 'rb'))
      cls_r_prob = np.float32(cls_r_prob)
      cls_a_prob = pickle.load(open('data/graph/vg_graph_a.pkl', 'rb'))
      cls_a_prob = np.float32(cls_a_prob)
  elif args.dataset == "ade":
      args.imdb_name = "ade_train_5"
      args.imdbval_name = "ade_val_5"
      args.set_cfgs = ['ANCHOR_SCALES', '[2, 4, 8, 16, 32]', 'MAX_NUM_GT_BOXES', '50']
      cls_r_prob = pickle.load(open('data/graph/ade_graph_r.pkl', 'rb'))
      cls_r_prob = np.float32(cls_r_prob)
      cls_a_prob = pickle.load(open('data/graph/ade_graph_a.pkl', 'rb'))
      cls_a_prob = np.float32(cls_a_prob)
  elif args.dataset == "vgbig":
      args.imdb_name = "vg_train_big"
      args.imdbval_name = "vg_val_big"
      args.set_cfgs = ['ANCHOR_SCALES', '[2, 4, 8, 16, 32]', 'MAX_NUM_GT_BOXES', '50']
      cls_r_prob = pickle.load(open('data/graph/vg_big_graph_r.pkl', 'rb'))
      cls_r_prob = np.float32(cls_r_prob)
      cls_a_prob = pickle.load(open('data/graph/vg_big_graph_a.pkl', 'rb'))
      cls_a_prob = np.float32(cls_a_prob)

看这里并没有写上coco和pascal voc的数据集

**Comment by chanyn** [comment]
You can edit files of training and testing for COCO and VOC following VG and ADE, we have provided corresponding gt graph of these two datasets. Same settings are used for all datasets in our paper.
