### ISSUE TITLE
Attribute & Relationship Knowledge GroundTruth making for custom dataset

### ISSUE THREAD

**Issue by PCML-WangZhe** [chanyn/HKRM#7]
I read the instruction about how to make GT for pascal voc and coco dataset, but it seems like there is no way to make gt for custom dataset, is it right?

**Comment by chanyn** [comment]
We try two methods to make gt for other dataset. One method need other dataset classes are obtained by VG classes (we just use VG top 3000 classes). Another method transform VG class knowledge gt to custom dataset according to cosine similarity of word embedding. But some classes name consisted of above 2 words can not be found word embedding.
