### ISSUE TITLE
 how can I make these two kinds of knowledge graphs？

### ISSUE THREAD

**Issue by AHUgaoyuan** [chanyn/HKRM#9]
Hello, I am very interested in your work, so I want to use your method to test my data set (VOC format), so how do I make these two kinds of knowledge graphs?Looking forward to your reply, thank you!

**Comment by chanyn** [comment]
Thanks for your attention. Now we update download link of graphs of coco and voc. And we also provided graph transfer code in 'lib/tools/collect_coco_voc_gtgraph.py'.

**Comment by summerrr** [comment]
so where is the 'lib/tools/collect_coco_voc_gtgraph.py'. @chanyn

**Comment by chanyn** [comment]
Sorry, i need to correct that code is in 'lib/datasets/tools/collect_coco_voc_gtgraph.py'.
